### ISSUE TITLE
Add support for Flutter 3

### ISSUE THREAD

**Issue by hmukwana** [douglasiacovelli/page_view_dot_indicator#10]
Current version generates warnings when getting compiled with Flutter 3.

**Comment by hmukwana** [comment]
Sometimes completely fails to build

**Comment by srcho** [comment]
same issue. like this

Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
../…/src/indicator.dart:89
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
    SchedulerBinding.instance!.addPostFrameCallback((_) {

**Comment by douglasiacovelli** [comment]
Hey Guys! I believe I can take a look at it today, but it shouldn't be too hard to update it.

**Comment by douglasiacovelli** [comment]
@hmukwana @srcho can you please test it again after updating the lib to 2.0.0?

**Comment by srcho** [comment]
@douglasiacovelli I just tested it and it works well 2.0.0. Thank you.

**Comment by douglasiacovelli** [comment]
Awesome! Thanks for the feedback ;)
